services:
  cveguard:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - ollama
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=cveguard;user=root;password=rootpassword
    ports:
      - "3333:8080"
      - "3334:8081"
    networks:
      - internal_network
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cveguard
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_network

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    healthcheck:
      test: ollama --version || exit 1
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull deepseek-r1 && wait"]
    networks:
      - internal_network

volumes:
  mysql_data:
  ollama:

networks:
  internal_network:
    driver: bridge